[tool.semantic_release]
version_variable = "src/__init__.py:__version__"
version_source = "tag"
upload_to_pypi = false
upload_to_release = false
changelog_file = "CHANGELOG.md"
commit_author = "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

[tool.semantic_release.branches.main]
match = "release"
