name: Semantic Version Calculation

on:
  pull_request:
    branches: [ "main" ]

jobs:
  calculate-semver:
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.workflow }}-calculate-semver-${{ github.head_ref }}
        cancel-in-progress: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
        
      - name: Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.21.0
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
          commit: true
          tag: false
          push: true
          changelog: true
