name: Check Python Dependency Conflicts

on:
  pull_request:
    branches: [ "main" ]

jobs:
  dependency-conflict-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install pipgrip
        run: pip install pipgrip

      - name: Check for conflicts in requirements.txt
        run: |
          if [ -f requirements.txt ]; then pipgrip -r requirements.txt --dry-run; fi

      - name: Check for conflicts in .dev/requirements.txt
        run: |
          if [ -f ./.dev/requirements.txt ]; then pipgrip -r ./.dev/requirements.txt --dry-run; fi
