name: Python Check Packages Conflicts

on:
    #push:
      #branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  check-packages-conficts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
  
          if [ -f ./.dev/requirements.txt ]; then pip install -r ./.dev/requirements.txt; fi
  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check dependencies conflicts
        run: |
          python -m pip check