# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Continous Integration and Deployment (CI/CD)


on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]


permissions:
  id-token: write
  contents: write
  issues: write
  packages: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          if [ -f ./.dev/requirements.txt ]; then pip install -r ./.dev/requirements.txt; fi

          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check dependencies conflicts
        run: |
          python -m pip check
    
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
      - name: Test with pytest
        run: |
          export CONFIG_PATH=$(pwd)/config/config.test.jsonc
          export PYTHONPATH=$(pwd)/src
          pytest -v ./tests/

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Save Docker image as tar
        run: |
          docker build -t ggsbot:latest .
          docker save ggsbot:latest -o ggsbot.tar

      - name: Save Docker image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ggsbot.tar

  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false
    needs:
      - test
      - build
      

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout Repository on Release Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Verify upstream has NOT changed
        run: |
          git fetch origin main
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
            echo "::error::main branch has changed during CI, aborting release."
            exit 1
          fi

      - name: Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.21.0
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
          commit: true
          tag: false
          push: false
          changelog: true
         
      - name: Create a New Branch for Version Update
        run: |
          git checkout -b release-version-${{ steps.release.outputs.tag }}
          git add .
          git commit -m "Release version ${{ steps.release.outputs.tag }}"
          git push origin release-version-${{ steps.release.outputs.tag }}

      - name: Create Pull Request for Release
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Release Version ${{ steps.release.outputs.tag }}"
          body: "This PR contains the version update for ${{ steps.release.outputs.tag }}."
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --auto
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Tag Docker image with version
        if: steps.release.outputs.released == 'true'
        run: |
          docker load -i ./ggsbot.tar
          docker tag ggsbot:latest ggsbot:${{ steps.release.outputs.tag }}
      
      - name: Create GitHub Release
        if: steps.release.outputs.released == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: ./ggsbot.tar
          tag_name: ${{ steps.release.outputs.tag }}