name: Continuous Integration and Deployment (CI/CD)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  issues: write
  packages: write

jobs:
  semver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install semantic-release
        run: |
          pip install python-semantic-release

      - name: Bump version and update changelog
        run: semantic-release version --changelog --no-vcs-release --no-tag

  test:
    if: startsWith(github.ref_name, 'release/')
    runs-on: ubuntu-latest
    needs: semver

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ./.dev/requirements.txt ]; then pip install -r ./.dev/requirements.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check dependencies conflicts
        run: python -m pip check

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          export CONFIG_PATH=$(pwd)/config/config.test.jsonc
          export PYTHONPATH=$(pwd)/src
          pytest -v ./tests/

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(cat src/__init__.py | grep '__version__' | cut -d '"' -f 2)
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Build and Save Docker image as tar
        run: |
          docker build -t ggsbot:${{ steps.extract_version.outputs.version }} .
          docker save ggsbot:${{ steps.extract_version.outputs.version }} -o ggsbot.tar

      - name: Save Docker image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ggsbot.tar

  release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false
    needs:
      - build

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./ggsbot.tar
          tag_name: ${{ needs.build.outputs.version }}
