name: Check Python Dependency Conflicts

on:
  push:
    branches: 
      - "dev"
    paths:
      - "**/*requirements.txt"
  pull_request:
    branches:
      - "dev"
    paths:
      - "**/*requirements.txt"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      modified_files: ${{ steps.find-files.outputs.modified_files }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find modified requirements files
        id: find-files
        run: |
          modified_files=$(git diff --name-only $GITHUB_SHA^ $GITHUB_SHA | grep 'requirements\.txt$')
          echo "modified_files=[\"$modified_files\"]" >> $GITHUB_OUTPUT
          echo $modified_files


  dependency-conflict-check:
    runs-on: ubuntu-latest
    needs: setup

    strategy:
      fail-fast: false
      matrix:
        # Python versions to test against [Version, raise]
        python-version: [["3.9.*", false], ["3.10.*", false], ["3.11.*", false], ["3.12.*", true]]
        requirements-file: ${{ fromJson(needs.setup.outputs.modified_files) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version[0] }}

      - name: Cache pip packages
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pipgrip
        run: pip install pipgrip

      - name: Check for dependency conflicts in "${{ matrix.requirements-file }}"" with Python version "${{ matrix.python-version[0] }}"
        id: check-dependencies
        run: |
          output=$(pipgrip --tree -r "${{ matrix.requirements-file }}")
          
          if [ $? == 0 ]; then
            echo $output
            echo "No dependency conflicts found."
            exit 0
          elif [ ${{ matrix.python-version[1] }} == "true" ] && [ $? != 0 ]; then
            echo $output
            echo "Dependency conflicts found."
            exit 1
          else
            echo $output
            echo "Dependency conflicts found."
            exit 0
          fi