name: Check Python Dependency Conflicts

on:
  push:
    branches: 
      - "dev"
    paths:
      - "requirements.txt"
      - ".dev/requirements.txt"
  pull_request:
    branches:
      - "dev"
    paths:
      - "requirements.txt"
      - ".dev/requirements.txt"

jobs:
  dependency-conflict-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9.0", "3.10.0", "3.11.0", "3.12.0"]
        requirements-file: 
          - requirements.txt
          - .dev/requirements.txt

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipgrip
        run: pip install pipgrip

      - name: Check for conflicts in ${{ matrix.requirements-file }}
        run: |
          if [ -f "${{ matrix.requirements-file }}" ]; 
            then pipgrip --tree-ascii -r ${{ matrix.requirements-file }}; 
          fi
