name: Publish Release

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  pull-requests: write
  contents: write

concurrency:
  group: build-and-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest

    steps:
      - name: Extract version from branch name
        id: extract_version
        run: |
          VERSION="${{ github.event.pull_request.head.ref }}"
          VERSION="${VERSION#release/}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Save Docker image as tar
        run: |
            docker build -t ggsbot:${{ steps.extract_version.outputs.version }} .
            docker save ggsbot:${{ steps.extract_version.outputs.version }} -o ggsbot.tar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
            files: ./ggsbot.tar
            tag_name: v${{ steps.extract_version.outputs.version }}
