name: Tag After Merge

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  tag:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important to create tags

      - name: Extract version from branch name
        id: extract
        run: |
          VERSION="${{ github.event.pull_request.head.ref }}"
          VERSION="${VERSION#release/}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag "v${{ steps.extract.outputs.version }}"
          git push origin "v${{ steps.extract.outputs.version }}"
